### ISSUE TITLE
Does not working :[

### ISSUE THREAD

**Issue by davoodkharmanzar** [Kink3d/kMotion#6]
hi dear,
it does not working on 2019.3.0f6 + URP 7.1.8 ...
no errors ...
but no effect in editor ... [PC]
and got black screen on IL2CPP PC build :[

**Comment by EsiNikko** [comment]
It's not meant to work in the scene view but game view.
Disable camera Post Processing flag and check if it's working.

**Comment by davoodkharmanzar** [comment]
thanks for your reply :]

i just did use your hotfix  
> **changed "renderPassEvent" from "AfterRenderingPostProcessing" to "BeforeRenderingPostProcessing" in MotionBlurRenderPass.cs**

and now everything working great in editor :]
but i have problem on IL2CPP build ...
everything is black!!

**Comment by EsiNikko** [comment]
I'll be happy to help.
What is the target device? It's working on iOS.

**Comment by davoodkharmanzar** [comment]
PC

**Comment by EsiNikko** [comment]
I'll give it a try and let you know if I had any solution.

**Comment by Kink3d** [comment]
Hi, I cant say i tried this with IL2CPP backend. Ill give it a try. Thanks for helping out @EsiNikko, whats the reason behind switching to before rendering post processing? Neither is right ( :( ) but i thought after would be the lesser of two evils...

**Comment by EsiNikko** [comment]
Found the solution.
Just add the shaders to pr-load in playersettings -> other settings, and build.

![Screenshot (18)](https://user-images.githubusercontent.com/23568386/74220423-d2abd900-4cc4-11ea-8c5d-a5fae87d25e4.jpg)

**Comment by EsiNikko** [comment]
Thanks @Kink3d .
When I use "AfterRenderingPostProcessing", I see no motion blur on the output. With looking at frame debugger I noticed that the Motion Blur pass is working correctly:
![Motion Blur pass is working correctly](https://user-images.githubusercontent.com/23568386/74247527-71532c80-4cfb-11ea-8ca7-e7abd76769c4.jpg)

But somehow the final pass of post-processing don't:
![Final pass of post-processing don't](https://user-images.githubusercontent.com/23568386/74247647-9cd61700-4cfb-11ea-9254-94282f794ea1.jpg)

I saw no reason behind "AfterRenderingPostProcessing", so I changed it to "BeforeRenderingPostProcessing" to effect _CameraColorTexture before entering post-processing passes and it worked correctly.

**Comment by davoodkharmanzar** [comment]
nice :]
its working now :]
